name: LaTeX

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install
      run: apt install texlive
    - name: pdf
      run: pdflatex main.tex
    - name: ls
      run: ls main.pdf
